# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ee066fb27a82b2fbfdc8701e35f13b2612923290fa1d427385043e2bd702cfeedba79278ed8ad099bc9749dd9d79fe3bded978ba80e14a93ff356d86f4c206e0

test:
  secret_key_base: 6c2aa452832e2c108f12c679f70e611e22da0815bafa456955880fcb9c19721797b149dd52fba525807d600098d58c738dbb88f9b8113509ad2f8d046032d1ce

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
